server.port=8080
spring.application.name=java-maven-app

# Expose les endpoints Actuator pour Prometheus
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
